### ISSUE TITLE
Any plans to open-source?

### ISSUE THREAD

**Issue by JunweiLiang** [Improbable-AI/learning-compliance#1]
Hi!

Your[ ICRA 2024 work](https://tif-twirl-13.github.io/learning-compliance) is quite impressive and we would love to build on top of your research! Do you have any plans to open-source? I see this repo is empty

Thanks,
Junwei

**Comment by gmargo11** [comment]
Hi @JunweiLiang ,

Thanks for your patience and interest in this project! We've just uploaded the training code.

-Gabe
