### ISSUE TITLE
About play and deploy

### ISSUE THREAD

**Issue by Zhihaibi** [Improbable-AI/learning-compliance#2]
Hi!

Your work is quite impressive. I try to using the play.py but fail (misiing the  eval_utils). Is there a missing file？And will the deploy code open-source too?

Thanks,
zhihai

**Comment by Hughshy** [comment]
I meet the same question about `eval_utils`, we can communicate with each other if have any solution.

**Comment by Zhihaibi** [comment]
> I meet the same question about `eval_utils`, we can communicate with each other if have any solution.

sure, welcome to contact me via the email.

**Comment by George-Gwj** [comment]
I also meet the same question.
